### ISSUE TITLE
Weird behavior when loading data from a bank to GRF_As

### ISSUE THREAD

**Issue by yongwonshin** [SAITPublic/PIMSimulator#7]
Hi, I'm confused with a behavior for the simulator with multi-channels.

When I replace `num_pim_chans_` to `1` in [src/tests/PIMKernel.cpp:446](https://github.com/SAITPublic/PIMSimulator/blob/dev/src/tests/PIMKernel.cpp#L446), I expect that the latency decreases as the total data movement is decreased by a factor of the number of channels. But the simulation cycle is the same as the original one (`num_pim_chans_` as `64`).

If this is not a bug, I think there are two possibilities:
1. A  broadcasting logic for loading data from a bank to GRFs (multiple PIM blocks) is not documented (repo and paper).
2. Input data are copied to each channel before starting kernel execution.

I've reviewed PIMLibrary, and it seems that case 2 is not present. I await your clarification.

Thank you.

**Comment by iamshcha** [comment]
If you simply replaced 64 channels with 1 channel in [src/tests/PIMKernel.cpp:446](https://github.com/SAITPublic/PIMSimulator/blob/dev/src/tests/PIMKernel.cpp#L446), the latency would be the same, because in this case you only ran 1 of the 64 channel parallelizations.

As for your second question, you are correct that the input data (if you mean the input vector for the GEMV operation) is copied to each channel. 
However, the input vectors are not written before the start of kernel execution as you mentioned. Due to the limited size of the input registers, the input vectors are written to the registers in tiles while the GEMV kernel is running. Prior to the MAC operation, the input vector is written to the registers through each channel.  The same applies to the PIMLibrary.

**Comment by yongwonshin** [comment]
I misunderstood the data movement of the input vectors. Thank you!
